FROM webdevops/php-apache-dev:8.2

COPY ./ /app

RUN apt-get update &&\
    apt-get install --no-install-recommends --assume-yes --quiet ca-certificates curl git &&\
    rm -rf /var/lib/apt/lists/* \
