services:
  simpler_web:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: simpler_web
    user: root
    restart: always
    volumes:
      - "./:/app:cached"
    environment:
      - WEB_ALIAS_DOMAIN=simpler.loc
      - WEB_DOCUMENT_ROOT=/app/upload
      - PHP_DATE_TIMEZONE=EST
      - PHP_DISPLAY_ERRORS=1
      - PHP_MEMORY_LIMIT=2048M
      - PHP_MAX_EXECUTION_TIME=300
      - PHP_POST_MAX_SIZE=500M
      - PHP_UPLOAD_MAX_FILESIZE=1024M
      - PHP_SENDMAIL_PATH='/usr/bin/mhsendmail --smtp-addr simpler_mail:1025'
      - PHP_DEBUGGER=xdebug
      - XDEBUG_REMOTE_CONNECT_BACK=0
      - XDEBUG_REMOTE_HOST=192.168.1.2
      - XDEBUG_REMOTE_PORT=9000
      - XDEBUG_CLIENT_PORT=9000
      - XDEBUG_CLIENT_HOST=192.168.1.2
      - php.xdebug.remote_enable=1
      - php.xdebug.idekey=PHPSTORM
    ports:
      - "80:80"
      - "443:443"
      - "32834:22"
  simpler_db:
    image: mariadb:10
    container_name: simpler_db
    restart: always
    volumes:
      - ./db-data:/var/lib/mysql:delegated
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=simpler_db
    ports:
      - "33067:3306"
  simpler_phpmyadmin:
    image: phpmyadmin
    container_name: simpler_phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1